// =============================================================================
//    Copyright (c) 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================
//! Persisted measurement aliases for supported quantity families.

mod acceleration;
mod amount_of_substance;
mod angle;
mod angular_velocity;
mod area;
mod capacitance;
mod catalytic_activity;
mod catalytic_activity_concentration;
mod dynamic_viscosity;
mod electric_charge;
mod electric_current;
mod electric_current_density;
mod electric_field;
mod electric_potential;
mod voltage;

mod electrical_conductance;
mod electrical_conductivity;
mod electrical_resistance;
mod electrical_resistivity;
mod energy;
mod force;
mod frequency;
mod heat_capacity;
mod heat_flux_density;
mod illuminance;
mod inductance;
mod information;
mod kinematic_viscosity;
mod length;
mod luminance;
mod luminous_intensity;
mod magnetic_field_strength;
mod magnetic_flux;
mod magnetic_flux_density;
mod mass;
mod mass_concentration;
mod mass_density;
mod mass_rate;
mod molality;
mod molar_concentration;
mod molar_mass;
mod molar_volume;
mod power;
mod pressure;
mod radioactivity;
mod solid_angle;
mod specific_heat_capacity;
mod specific_radioactivity;
mod surface_tension;
mod temperature;
mod temperature_interval;
mod thermal_conductivity;
mod thermal_resistance;
mod time;
mod torque;
mod velocity;
mod volume;
mod volume_rate;

pub use acceleration::Acceleration;
pub use amount_of_substance::AmountOfSubstance;
pub use angle::Angle;
pub use angular_velocity::AngularVelocity;
pub use area::Area;
pub use capacitance::Capacitance;
pub use catalytic_activity::CatalyticActivity;
pub use catalytic_activity_concentration::CatalyticActivityConcentration;
pub use dynamic_viscosity::DynamicViscosity;
pub use electric_charge::ElectricCharge;
pub use electric_current::ElectricCurrent;
pub use electric_current_density::ElectricCurrentDensity;
pub use electric_field::ElectricField;
pub use electric_potential::ElectricPotential;
pub use electrical_conductance::ElectricalConductance;
pub use electrical_conductivity::ElectricalConductivity;
pub use electrical_resistance::ElectricalResistance;
pub use electrical_resistivity::ElectricalResistivity;
pub use energy::Energy;
pub use force::Force;
pub use frequency::Frequency;
pub use heat_capacity::HeatCapacity;
pub use heat_flux_density::HeatFluxDensity;
pub use illuminance::Illuminance;
pub use inductance::Inductance;
pub use information::Information;
pub use kinematic_viscosity::KinematicViscosity;
pub use length::Length;
pub use luminance::Luminance;
pub use luminous_intensity::LuminousIntensity;
pub use magnetic_field_strength::MagneticFieldStrength;
pub use magnetic_flux::MagneticFlux;
pub use magnetic_flux_density::MagneticFluxDensity;
pub use mass::Mass;
pub use mass_concentration::MassConcentration;
pub use mass_density::MassDensity;
pub use mass_rate::MassRate;
pub use molality::Molality;
pub use molar_concentration::MolarConcentration;
pub use molar_mass::MolarMass;
pub use molar_volume::MolarVolume;
pub use power::Power;
pub use pressure::Pressure;
pub use radioactivity::Radioactivity;
pub use solid_angle::SolidAngle;
pub use specific_heat_capacity::SpecificHeatCapacity;
pub use specific_radioactivity::SpecificRadioactivity;
pub use surface_tension::SurfaceTension;
pub use temperature::Temperature;
pub use temperature_interval::TemperatureInterval;
pub use thermal_conductivity::ThermalConductivity;
pub use thermal_resistance::ThermalResistance;
pub use time::Time;
pub use torque::Torque;
pub use velocity::Velocity;
pub use voltage::Voltage;
pub use volume::Volume;
pub use volume_rate::VolumeRate;
